### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [5outh/5outh.github.io-old#1]
I would like to be able to follow an Atom or RSS feed of your posts. Hakyll supports this out of the box: https://jaspervdj.be/hakyll/tutorials/05-snapshots-feeds.html

**Comment by 5outh** [comment]
I had it at one point - removed it in a refactor for some reason; I'll add it back for sure. Thanks for voicing your interest!

**Comment by 5outh** [comment]
@tfausak Done! Links to atom/rss feeds in the header: http://www.kovach.me/
